package modelo;
// Generated 20/03/2018 03:22:25 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Respuesta generated by hbm2java
 */
public class Respuesta  implements java.io.Serializable {


     private int idrespuesta;
     private Pregunta pregunta;
     private Usuario usuario;
     private Date fecha;
     private String contenido;

    public Respuesta() {
    }

	
    public Respuesta(int idrespuesta, Pregunta pregunta) {
        this.idrespuesta = idrespuesta;
        this.pregunta = pregunta;
    }
    public Respuesta(int idrespuesta, Pregunta pregunta, Usuario usuario, Date fecha, String contenido) {
       this.idrespuesta = idrespuesta;
       this.pregunta = pregunta;
       this.usuario = usuario;
       this.fecha = fecha;
       this.contenido = contenido;
    }
   
    public int getIdrespuesta() {
        return this.idrespuesta;
    }
    
    public void setIdrespuesta(int idrespuesta) {
        this.idrespuesta = idrespuesta;
    }
    public Pregunta getPregunta() {
        return this.pregunta;
    }
    
    public void setPregunta(Pregunta pregunta) {
        this.pregunta = pregunta;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public String getContenido() {
        return this.contenido;
    }
    
    public void setContenido(String contenido) {
        this.contenido = contenido;
    }




}


