package modelo;
// Generated 20/03/2018 03:22:25 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private String username;
     private String nombre;
     private String paterno;
     private String materno;
     private String carrera;
     private Date fecharegistro;
     private String contrasena;
     private String correo;
     private Boolean rol;
     private Set preguntas = new HashSet(0);
     private Set respuestas = new HashSet(0);

    public Usuario() {
    }

	
    public Usuario(String username) {
        this.username = username;
    }
    public Usuario(String username, String nombre, String paterno, String materno, String carrera, Date fecharegistro, String contrasena, String correo, Boolean rol, Set preguntas, Set respuestas) {
       this.username = username;
       this.nombre = nombre;
       this.paterno = paterno;
       this.materno = materno;
       this.carrera = carrera;
       this.fecharegistro = fecharegistro;
       this.contrasena = contrasena;
       this.correo = correo;
       this.rol = rol;
       this.preguntas = preguntas;
       this.respuestas = respuestas;
    }
   
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getPaterno() {
        return this.paterno;
    }
    
    public void setPaterno(String paterno) {
        this.paterno = paterno;
    }
    public String getMaterno() {
        return this.materno;
    }
    
    public void setMaterno(String materno) {
        this.materno = materno;
    }
    public String getCarrera() {
        return this.carrera;
    }
    
    public void setCarrera(String carrera) {
        this.carrera = carrera;
    }
    public Date getFecharegistro() {
        return this.fecharegistro;
    }
    
    public void setFecharegistro(Date fecharegistro) {
        this.fecharegistro = fecharegistro;
    }
    public String getContrasena() {
        return this.contrasena;
    }
    
    public void setContrasena(String contrasena) {
        this.contrasena = contrasena;
    }
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }
    public Boolean getRol() {
        return this.rol;
    }
    
    public void setRol(Boolean rol) {
        this.rol = rol;
    }
    public Set getPreguntas() {
        return this.preguntas;
    }
    
    public void setPreguntas(Set preguntas) {
        this.preguntas = preguntas;
    }
    public Set getRespuestas() {
        return this.respuestas;
    }
    
    public void setRespuestas(Set respuestas) {
        this.respuestas = respuestas;
    }




}


